import { NgModule } from '@angular/core';
import {
    MatButtonModule,
    MatToolbarModule,
    MatSidenavModule,
    MatListModule,
    MatIconModule,
    MatTableModule,
    MatTooltipModule,
    MatFormFieldModule,
    MatInputModule,
    MatSortModule,
    MatPaginatorModule,
    MatSelectModule,
    MatRadioModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSlideToggleModule,
    MatDialogModule,
    MatCardModule,
    MatBottomSheetModule,
    MatMenuModule,
    MatDividerModule,
    MatSnackBarModule,
    MatProgressSpinnerModule,
    MatGridListModule
} from '@angular/material'

@NgModule({
    imports: [MatButtonModule,
        MatToolbarModule,
        MatSidenavModule,

        MatListModule,
        MatIconModule,
        MatTableModule,
        MatTooltipModule,
        MatFormFieldModule,
        MatInputModule,
        MatSortModule,
        MatPaginatorModule,
        MatSelectModule,
        MatRadioModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatSlideToggleModule,
        MatDialogModule,
        MatCardModule,
        MatBottomSheetModule,
        MatMenuModule,
        MatDividerModule,
        MatSnackBarModule,
        MatProgressSpinnerModule,
        MatGridListModule],
    exports: [MatButtonModule,
        MatToolbarModule,
        MatSidenavModule,

        MatListModule,
        MatIconModule,
        MatTableModule,
        MatTooltipModule,
        MatFormFieldModule,
        MatInputModule,
        MatSortModule,
        MatPaginatorModule,
        MatSelectModule,
        MatRadioModule,
        MatDatepickerModule,
        MatSlideToggleModule,
        MatDialogModule,
        MatCardModule,
        MatBottomSheetModule,
        MatMenuModule,
        MatDividerModule,
        MatSnackBarModule,
        MatProgressSpinnerModule,
        MatGridListModule]
})
export class MaterialModule {
}